// <auto-generated />
using System;
using BacklogGames.DataAccess.Layer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BacklogGames.DataAccess.Layer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218180814_AddCompletedAtToUserListGame")]
    partial class AddCompletedAtToUserListGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BacklogApp.DataAccess.Layer.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long?>("FirstReleaseDate")
                        .HasColumnType("bigint");

                    b.Property<int>("IgdbId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IgdbId")
                        .IsUnique()
                        .HasDatabaseName("IX_Game_IgdbId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BacklogGames.DataAccess.Layer.Models.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("GameStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Name = "En Progreso"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completado"
                        });
                });

            modelBuilder.Entity("BacklogGames.DataAccess.Layer.Models.UserList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserList");
                });

            modelBuilder.Entity("BacklogGames.DataAccess.Layer.Models.UserListGame", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("UserListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("GameId", "UserListId");

                    b.HasIndex("GameStatusId");

                    b.HasIndex("UserListId");

                    b.ToTable("UserListGames");
                });

            modelBuilder.Entity("BacklogGames.DataAccess.Layer.Models.UserListGame", b =>
                {
                    b.HasOne("BacklogApp.DataAccess.Layer.Models.Game", "Game")
                        .WithMany("UserListGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklogGames.DataAccess.Layer.Models.GameStatus", "GameStatus")
                        .WithMany("UserListGames")
                        .HasForeignKey("GameStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BacklogGames.DataAccess.Layer.Models.UserList", "UserList")
                        .WithMany("UserListGames")
                        .HasForeignKey("UserListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameStatus");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("BacklogApp.DataAccess.Layer.Models.Game", b =>
                {
                    b.Navigation("UserListGames");
                });

            modelBuilder.Entity("BacklogGames.DataAccess.Layer.Models.GameStatus", b =>
                {
                    b.Navigation("UserListGames");
                });

            modelBuilder.Entity("BacklogGames.DataAccess.Layer.Models.UserList", b =>
                {
                    b.Navigation("UserListGames");
                });
#pragma warning restore 612, 618
        }
    }
}
